### ISSUE TITLE
[question] Is there a way to test generators written in typescript with yeoman-test?

### ISSUE THREAD

**Issue by aanno** [yeoman/yeoman-test#105] opened 2020-05-08 11:10 UTC
Is there a way to test generators written in typescript with yeoman-test?

When I try something like
```typescript
run(join(__dirname, '../generators/app'))
```
I've got an error:
```
Uncaught Error: You don't seem to have a generator with the name “jhipster-module-aanno:app” installed.
```
Hence it is perhaps better to pass the constructor there. But I don't know to do that, i.e. the following is _wrong_:

```typescript
import {MyGenerator} from "../generators/app"
...
run(Generator)
```

**Comment by aanno** [comment] 2020-05-08 11:30
And when I even try:

```typescript
import {Constructor, run} from "yeoman-test"
import {Generator} from "yeoman-generator"
import {MyGenerator} from "../generators/app"

const generator: Constructor<Generator> = MyGenerator.new
run(generator, {resolved: true})
```

I ended up with
```
Uncaught TypeError: Cannot read property 'createGenerator' of undefined
```

**Comment by mshima** [comment] 2020-05-08 12:12
> Is there a way to test generators written in typescript with yeoman-test?
> 
> When I try something like
> 
> ```ts
> run(join(__dirname, '../generators/app'))
> ```
> 
> I've got an error:
> 
> ```
> Uncaught Error: You don't seem to have a generator with the name “jhipster-module-aanno:app” installed.
> ```

Make sure your generator folder is called `generator-jhipster-module-aanno`.

Otherwise you should register the namespace with the generator.

**Comment by aanno** [comment] 2020-05-08 15:59
Well, the directory name is ok. I finally found 2 issues:

* `tsconfig.json` target must be at least `es6`. See [stackoverflow](https://stackoverflow.com/questions/51860043/javascript-es6-typeerror-class-constructor-client-cannot-be-invoked-without-ne) for the explanation.
* Code should be like this
```typescript
import {describe, beforeEach} from "mocha"
import {join} from "path"
import {copySync} from "fs-extra"
import {file} from "yeoman-assert"
import {Constructor, run} from "yeoman-test"
// import {Generator} from "yeoman-generator"
import {MyGenerator} from "../generators/app"

describe('JHipster generator aanno', () => {
  // const generator: Constructor<Generator> = MyGenerator.new
  describe('Test with Maven and AngularX', () => {
    beforeEach(done => {
      // run(join(__dirname, '../generators/app'))
      run(MyGenerator as any)
  ...
```
  The `as any` seems to indicate that the type definition in `@types/yeoman-test` is wrong.

**Comment by mshima** [comment] 2020-05-25 19:41
Looks like the problem is with yeoman-test type definition.
Closing.

**Closed by mshima** 2020-05-25 19:41 UTC
