### ISSUE TITLE
Prompt helper function/option `validate` is not getting executed when using `withPrompts`

### ISSUE THREAD

**Issue by subeeshcbabu** [yeoman/yeoman-test#1] opened 2016-01-09 00:34 UTC
Prompt:

```
let prompts = [
   {
      name: 'hello',
      type: 'input',
      validate: function(input) {
         // Not getting executed with the `yeomen-test` unit test
         return "Wrong Input";
      }
]
```

Unit test:

```
   helpers.run(path.join(__dirname, '../generators/app'))
        .withPrompts({hello: 'how are you'})       
        .on('end', done);
```

Looks like the `inquirer` module runs the `validate` on `submit`/`enter` event.
https://github.com/SBoudrias/Inquirer.js/blob/33403fca0078b4e1dcd4b0e185598cfe88550feb/lib/prompts/input.js#L39 

The dummy prompt provided by `yeomon-test` has to be extended to deal with the key stoke events and other functionalities?

**Comment by mischah** [comment] 2016-03-15 21:47
Same here. Would love to increase test coverage 😘

**Comment by mischah** [comment] 2016-03-15 21:52
Update. This is a duplicate of yeoman/generator#775 

Solution from there:

> Ah, I suppose I could refactor my validations into a separate validator object instead of including them as anonymous functions in the prompt declaration. Could then unit test those separately. That's a cleaner approach anyway.

@SBoudrias I love your new profile pic :relaxed:

**Comment by SBoudrias** [comment] 2016-03-15 22:09
@mischah hahaha thanks

Having separate functions will allow you to test them yeah.

I love a better test workflow for prompts, but I'm not sure how that'd work as these errors are not thrown, just displayed to the user as Inquirer ask for a valid answer. That means there's not really any place we can catch these to validate they've been thrown.

**Comment by mischah** [comment] 2016-11-25 17:41
Closing this because it works like a charm to test validations like this.

For future reference: 
- [Prompting helpers](https://github.com/micromata/generator-http-fake-backend/blob/master/generators/app/promptingHelpers.js)
- [Tests ](https://github.com/micromata/generator-http-fake-backend/blob/master/test/app.js#L94-L109)

**Closed by mischah** 2016-11-25 17:41 UTC
